apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kt-cloudnative/vue_crud_security:v2
        imagePullPolicy: Always
        env:
          - name: BACKEND_API_URL
            value: "backend" 
        ports:
        - containerPort: 80
